@echo off
echo Creating virtual environment...
python -m venv venv
echo Activating virtual environment...
call venv\Scripts\activate
echo Installing requirements...
pip install -r requirements.txt
echo Running model training script...
python ml_model/train_model.py
echo Setup complete!
pause
